// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4t3nob6lNivGLCUycyxP01S8lp6PP_eY',
    appId: '1:630148991230:web:28a241c39f1325c6917daf',
    messagingSenderId: '630148991230',
    projectId: 'bmiator',
    authDomain: 'bmiator.firebaseapp.com',
    storageBucket: 'bmiator.appspot.com',
    measurementId: 'G-LEBZ93MXPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAohkEereh3NxWxFxQ6e_dmmE6iO5WFZY',
    appId: '1:630148991230:android:af42c59d759b4980917daf',
    messagingSenderId: '630148991230',
    projectId: 'bmiator',
    storageBucket: 'bmiator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsdI8X4EgYMEA1zrZy95Zu36ObqfUITgg',
    appId: '1:630148991230:ios:68e33cc73744c5dd917daf',
    messagingSenderId: '630148991230',
    projectId: 'bmiator',
    storageBucket: 'bmiator.appspot.com',
    iosBundleId: 'com.example.bmiator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsdI8X4EgYMEA1zrZy95Zu36ObqfUITgg',
    appId: '1:630148991230:ios:68e33cc73744c5dd917daf',
    messagingSenderId: '630148991230',
    projectId: 'bmiator',
    storageBucket: 'bmiator.appspot.com',
    iosBundleId: 'com.example.bmiator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4t3nob6lNivGLCUycyxP01S8lp6PP_eY',
    appId: '1:630148991230:web:319a2650fa979bf3917daf',
    messagingSenderId: '630148991230',
    projectId: 'bmiator',
    authDomain: 'bmiator.firebaseapp.com',
    storageBucket: 'bmiator.appspot.com',
    measurementId: 'G-9T6GVCCBTM',
  );
}
